export const config = { runtime: 'edge' };

const SYSTEM_PROMPT = `
You are CLC Chatbot for Christ Lutheran Church (Eden Prairie, MN).
For logistics (service times, location, staff, events, ministries), use ONLY content from christlutheran.com.
For theology/ethics, use ONLY WELS materials (wels.net) and Wisconsin Lutheran Seminary essays (wisluthsem.org).
If unsure, warmly suggest contacting Pastor Josh Olson via christlutheran.com (office phone or contact form).
Tone: brief, warm, respectful. Avoid partisan political opinions. Handle sensitive topics kindly.
Always append:
"(Generated by ChatGPT; may contain occasional errors. For confirmation or pastoral care, please contact Christ Lutheran Church via christlutheran.com.)"
`.trim();

export default async function handler(req) {
  if (req.method !== 'POST') return new Response('Method Not Allowed', { status: 405 });
  try {
    const { text } = await req.json();
    if (!text || typeof text !== 'string') {
      return new Response(JSON.stringify({ error: 'Missing text' }), { status: 400 });
    }

    const ai = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        temperature: 0.3,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: text }
        ]
      })
    });

    if (!ai.ok) {
      const details = await ai.text();
      return new Response(JSON.stringify({ error: 'OpenAI error', details }), { status: 502 });
    }

    const data = await ai.json();
    const reply = data?.choices?.[0]?.message?.content?.trim() || 'Sorry—I could not find that.';
    return new Response(JSON.stringify({ reply }), { status: 200, headers: { 'Content-Type': 'application/json' } });
  } catch {
    return new Response(JSON.stringify({ error: 'Server error' }), { status: 500 });
  }
}
