// api/clc-chat.js — CLC Chatbot with local KB context (Markdown)
// Runtime: Node (Vercel root functions)
const fs = require('fs/promises');
const path = require('path');

const VERSION = 'kb-v1';
const KB_PATH = path.join(process.cwd(), 'data', 'ClcInfo.md');

// Simple in-memory cache so we only read the file once per lambda boot
let KB_CACHE = null;
async function loadKB() {
  if (KB_CACHE !== null) return KB_CACHE;
  try {
    const raw = await fs.readFile(KB_PATH, 'utf8');
    // Optional: trim overly large files (safety)
    const maxChars = 60_000; // ~10-12k tokens rough order; adjust if needed
    KB_CACHE = raw.length > maxChars ? raw.slice(0, maxChars) : raw;
  } catch (e) {
    // If file missing, keep null so health shows hasKB: false
    KB_CACHE = null;
  }
  return KB_CACHE;
}

const SYSTEM_PROMPT = `
You are the CLC Chatbot for Christ Lutheran Church (Eden Prairie, MN).

MISSION & SCOPE (STRICT)
• Logistics (service times, location/parking, staff, ministries, events): ONLY use christlutheran.com content and the provided “Context.”
• Theology/ethics/doctrine: ONLY use WELS materials (wels.net) and Wisconsin Lutheran Seminary essays (wisluthsem.org), or clearly marked doctrine in the provided “Context.”
• If the answer is not clearly supported by those sources, reply EXACTLY with the refusal line provided by the developer.

TONE & PASTORAL CARE
• Warm, welcoming, and kind. Plain language. Assume good intent.
• Default to concise 2–4 sentence answers. Offer: “I can share more details if you’d like.”
• For sensitive topics, be gentle and invite pastoral follow-up.

OPERATIONAL GUARDRAILS
• Never browse or rely on outside sources. Don’t invent details or summarize from memory.
• Benevolence/assistance: invite the person to use the contact form on christlutheran.com.
• Vendor solicitations: “Thanks for reaching out, we’re not seeking new professional services right now.”

FOOTER (always append):
"(Generated by ChatGPT; may contain occasional errors. For confirmation or pastoral care, please contact Christ Lutheran Church via christlutheran.com.)"
`.trim();

const STYLE_GUIDE = `
Style:
• Begin with a warm micro-greeting when appropriate (“Happy to help!” / “Thanks for asking.”).
• Answer directly first; then offer one optional next step (link or “would you like more details?”).
• Keep sentences short; avoid jargon; use “we” and “you” where natural.

Refusal:
• When sources don’t cover it, use the exact custom refusal line configured by the developer and add a gentle offer to connect with a person.
`.trim();

const FEW_SHOT = [
  {
    role: 'system',
    content:
`Example Q: What time are services?
Example A: Happy to help! Our Sunday worship is at 9:30 AM. We’re at 16900 Main Street in Eden Prairie, and parking is on the west side. I can share more details if you’d like.`
  },
  {
    role: 'system',
    content:
`Example Q: Do you offer Sunday School?
Example A: Yes! Sunday School meets at 10:35 AM following worship during the school year. If you’re bringing kids, I can share check-in details.`
  }
];

module.exports = async function handler(req, res) {
  // GET = health/version check (also shows KB status)
  if (req.method === 'GET') {
    const kb = await loadKB();
    return res.status(200).json({
      ok: true,
      version: VERSION,
      hasKey: Boolean(process.env.OPENAI_API_KEY),
      hasKB: Boolean(kb),
      kbBytes: kb ? kb.length : 0,
      node: process.version
    });
  }

  if (req.method !== 'POST') {
    return res.status(405).send('Method Not Allowed');
  }

  // Robust body parsing (handles cases where req.body isn't pre-parsed)
  let raw = '';
  await new Promise((resolve) => {
    req.on('data', (c) => (raw += c));
    req.on('end', resolve);
  });

  let text = '';
  try {
    const json = raw ? JSON.parse(raw) : (req.body || {});
    text = typeof json.text === 'string' ? json.text : '';
  } catch {
    return res.status(400).json({ error: 'Invalid JSON', version: VERSION });
  }
  if (!text) return res.status(400).json({ error: 'Missing text', version: VERSION });

  // Load local knowledge base
  const kb = await loadKB();

  // Build the message list with KB context (if present)
  // Keep context concise; the model should prioritize it.
  const messages = [
    { role: 'system', content: SYSTEM_PROMPT },
    ...(kb ? [{
      role: 'system',
      content:
        "CONTEXT (from data/ClcInfo.md — approved congregation info):\n" +
        kb +
        "\n\nUse ONLY this context for logistics, and ONLY WELS/WSL sources for doctrine. If the context does not contain the answer, use the refusal line."
    }] : []),
    { role: 'system', content: 'If sources/context are insufficient, use the refusal line verbatim. Do not improvise.' },
    { role: 'user', content: text }
  ];

  try {
    // Safety: check env var early
    if (!process.env.OPENAI_API_KEY) {
      return res.status(500).json({ error: 'OPENAI_API_KEY is not set', version: VERSION });
    }

    const aiRes = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        temperature: 0.25,
        messages
      })
    });

    const textBody = await aiRes.text();
    if (!aiRes.ok) {
      // Surface upstream error in JSON for easy debugging
      return res.status(502).json({
        error: 'OpenAI error',
        status: aiRes.status,
        statusText: aiRes.statusText,
        body: textBody.slice(0, 1200),
        version: VERSION
      });
    }

    let data;
    try { data = JSON.parse(textBody); }
    catch {
      return res.status(500).json({ error: 'Failed to parse OpenAI JSON', body: textBody.slice(0, 1200), version: VERSION });
    }

    const reply =
      data?.choices?.[0]?.message?.content?.trim() ||
      'I’m not certain based on our sources. Would you like to chat with a person?';

    const handoff = /i’m not certain based on our sources/i.test(reply);

    return res.status(200).json({ reply, handoff, version: VERSION, usedKB: Boolean(kb) });
  } catch (e) {
    return res.status(500).json({ error: 'Server error', details: String(e), version: VERSION });
  }
};
